[build-system]
requires = ["setuptools>=61"]
build-backend = "setuptools.build_meta"

[project]
name = "aion"
version = "0.0.1"
description = "AstronomIcal Omnimodal Network"
requires-python = ">=3.8"
dependencies = [
    "torch>=2.4.0",
    "diffusers==0.20.0",
    "einops>=0.7.0",
    "huggingface_hub>=0.20.0",
    "tokenizers>=0.15.2",
]
